### ISSUE TITLE
Transform in archive method makes slugs not runnable on Heroku

### ISSUE THREAD

**Issue by edeustace** [heroku/slug-compiler#4]
I've started using this gem to build my own slugs, but I had to override the archive function, specifically to remove: 

```
     "--xform", "s,^./,./app/,"
```

From:

```
system("tar", "czf", slug, "--xform", "s,^./,./app/,", "--owner=root",
         "--hard-dereference", "-C", build_dir, ".",
         [:out, :err] => "/dev/null") or raise("couldn't tar")
```

https://github.com/heroku/slug-compiler/blob/master/lib/slug_compiler.rb#L177

So that the slugs would run on the current heroku platform.

Not sure if this is an issue as you state that this gem isn't used on production at the moment, but would be interested to know what the future plans are, so that if slug compilation changes I can update my set up.

**Comment by technomancy** [comment]
Aha; yes, nice catch. Unfortunately while we want to have all slug compilation go through OSS component, we currently don't have any concrete plans to move forward on the development of this specific codebase in the short term.

I'm curious what you're doing to build your own slugs though, if you don't mind providing some detail there. Has this slug-compiler proven useful apart from the path issue?

**Comment by edeustace** [comment]
Hi, yes I've been building my own slugs and this project was very helpful!

We have a scala project and it was starting to take a long time to prep the app on heroku.

I created a gem that depends on `heroku/slug-compiler` and I subclass the compiler and override the archive method. The gem does a few other things we need like pulling source, creating folders, but nothing too fancy.

We then use the [heroku-anvil](https://github.com/ddollar/heroku-anvil), utility to expose the slugs to the heroku servers.

Overall I think providing a way for people so self build slugs is pretty attractive to me as a dev. If the release mechanism could be secured too - would be fantastic.
